apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLables:
      app: sample-app
  template:
    metadata:
      lables:
        app: sample-app
    spec:
      contaciners:
      - command:
        - /app/sample-app
        image: gitopsbook/sample-app:v0.1
        name: sample-app
        ports:
        - containerPort: 8080
